### ISSUE TITLE
I used React Native Navigation to have a kotlin Version conflict in this library. The following error occurred

### ISSUE THREAD

**Issue by skyliwq** [edeckers/react-native-blob-courier#106]
I used React Native Navigation to have a kotlin Version conflict in this library. The following error occurred: 

e: /Users/devin/Develop/app/KLT/node_modules/react-native-blob-courier/android/src/main/java/io/deckers/blob_courier/upload/UploaderParameterFactory.kt: (180, 13): Cannot infer a type for this parameter. Please specify it explicitly.
e: /Users/devin/Develop/app/KLT/node_modules/react-native-blob-courier/android/src/main/java/io/deckers/blob_courier/upload/UploaderParameterFactory.kt: (181, 12): Cannot infer a type for this parameter. Please specify it explicitly.
e: /Users/devin/Develop/app/KLT/node_modules/react-native-blob-courier/android/src/main/java/io/deckers/blob_courier/upload/UploaderParameterFactory.kt: (187, 13): Cannot infer a type for this parameter. Please specify it explicitly.
e: /Users/devin/Develop/app/KLT/node_modules/react-native-blob-courier/android/src/main/java/io/deckers/blob_courier/upload/UploaderParameterFactory.kt: (192, 36): Type mismatch: inferred type is ReadableMap? but ReadableMap was expected
e: /Users/devin/Develop/app/KLT/node_modules/react-native-blob-courier/android/src/main/java/io/deckers/blob_courier/upload/UploaderParameterFactory.kt: (193, 36): Type mismatch: inferred type is ReadableMap? but ReadableMap was expected
e: /Users/devin/Develop/app/KLT/node_modules/react-native-blob-courier/android/src/main/java/io/deckers/blob_courier/upload/UploaderParameterFactory.kt: (227, 15): 
Cannot infer a type for this parameter. Please specify it explicitly.

 I changed the kotlin Version 1.4.21 and the following error occurred again.

Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class kotlinx.coroutines.debug.AgentPremain found in modules jetified-kotlinx-coroutines-core-1.3.7 (org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.7) and jetified-kotlinx-coroutines-debug-1.3.2 (org.jetbrains.kotlinx:kotlinx-coroutines-debug:1.3.2)
     Duplicate class kotlinx.coroutines.debug.AgentPremain$installSignalHandler$1 found in modules jetified-kotlinx-coroutines-core-1.3.7 (org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.7) and jetified-kotlinx-coroutines-debug-1.3.2 (org.jetbrains.kotlinx:kotlinx-coroutines-debug:1.3.2)
     Duplicate class kotlinx.coroutines.debug.internal.DebugProbesImpl found in modules jetified-kotlinx-coroutines-core-1.3.7 (org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.7) and jetified-kotlinx-coroutines-debug-1.3.2 (org.jetbrains.kotlinx:kotlinx-coroutines-debug:1.3.2)
     Duplicate class kotlinx.coroutines.debug.internal.DebugProbesImpl$$special$$inlined$sortedBy$1 found in modules jetified-kotlinx-coroutines-core-1.3.7 (org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.7) and jetified-kotlinx-coroutines-debug-1.3.2 (org.jetbrains.kotlinx:kotlinx-coroutines-debug:1.3.2)
     Duplicate class kotlinx.coroutines.debug.internal.DebugProbesImpl$CoroutineOwner found in modules jetified-kotlinx-coroutines-core-1.3.7 (org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.7) and jetified-kotlinx-coroutines-debug-1.3.2 (org.jetbrains.kotlinx:kotlinx-coroutines-debug:1.3.2)
     Duplicate class kotlinx.coroutines.debug.internal.DebugProbesImpl$probeCoroutineCreated$frame$1$1 found in modules jetified-kotlinx-coroutines-core-1.3.7 (org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.7) and jetified-kotlinx-coroutines-debug-1.3.2 (org.jetbrains.kotlinx:kotlinx-coroutines-debug:1.3.2)

[https://wix.github.io/react-native-navigation/docs/installing](url)

**Comment by edeckers** [comment]
That highly likely to be a result of #104 as I introduced coroutines in the Android code base there; are you on version 1.0.7? You should be able to circumvent this issue for now by falling back to 1.0.6.

I'll look in to this later today, thanks for reporting.

**Comment by skyliwq** [comment]
I see. Thank you

**Comment by edeckers** [comment]
# First findings

The following libraries in `react-native-blob-courier` and `react-native-navigation` conflict in version numbers (1.3.2 vs 1.3.7) and Jetifier gets hung up on it:
- `org.jetbrains.kotlinx:kotlinx-coroutines-core`
- `org.jetbrains.kotlinx:kotlinx-coroutines-debug`

I could fix that by bumping 1.3.2 to 1.3.7, but that is just fighting symptoms: there will always be libraries that have conflicting dependencies. So possible solutions going forward will be to:
1. Proposing a viable workaround
2. Cut down on dependencies

With respect to (2), I already kept the amount of dependencies as small as possible. I only use the conflicting dependency for testing though, so I will see if removing it as a depency from the 'implementation' solves this particular issue.
 
As for (1), you can do this:

```diff
# file: app/build.gradle
(...)
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
+    implementation('org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.7') { force = true }
+    implementation('org.jetbrains.kotlinx:kotlinx-coroutines-debug:1.3.7') { force = true }
    implementation "com.facebook.react:react-native:+"  // From node_modules
(...)
```

**Comment by edeckers** [comment]
The solution to this problem was added to the "Common pitfalls" section of the Wiki:
https://github.com/edeckers/react-native-blob-courier/wiki/Common-pitfalls#dependency-conflicts

**Comment by edeckers** [comment]
@skyliwq I've removed the conflicting dependency from `implementation` and only use it in `testImplementation` and `androidTestImplementation`, resolves the problem you're having. I'll release version 1.0.8 containing this 'fix' (it isn't really a bug, just a dependency version conflict) soon.

Should you ever run into a dependency conflict with another library again you'll find an explanation on how to resolve it on the project wiki I mentioned in my previous comment.

Thank you once more for reporting the problem, it improved the Blob Courier a little further :)

**Comment by majirosstefan** [comment]
It seems that it's not working in Expo ejected app. Always got this error: 

main/java/io/deckers/blob_courier/upload/UploaderParameterFactory.kt: (113, 16): Type mismatch: inferred type is ReadableMap? but TypeVariable(T) was expected

Even when I have

```
implementation('org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.7') { force = true }
implementation('org.jetbrains.kotlinx:kotlinx-coroutines-debug:1.3.7') { force = true }

```

into build.gradle file. Any advice? 

"expo": "^39.0.0", "react-native": "~0.63.4", "react-native-blob-courier": "^3.0.0"

**Comment by edeckers** [comment]
Hi @majirosstefan! Your exception seems to differ slightly from the opening post: `TypeVariable(T) was expected` vs `ReadableMap was expected`. Can you include some stack trace for the build? Especially the part under `Execution failed for task ':app:checkDebugDuplicateClasses'`?

I think some dependencies other than `kotlinx-coroutines-*` might be conflicting.

**Comment by majirosstefan** [comment]
I have sent a pull request that fixes the issue for me - something with typecasting. Here: https://github.com/edeckers/react-native-blob-courier/pull/177

When I run app:checkDebugDuplicateClasses:

![Screen Shot 2021-12-23 at 8 33 38 PM](https://user-images.githubusercontent.com/44647381/147284699-786e0ac7-f155-4a4e-a02a-3ffb03d49c32.png)

![Screen Shot 2021-12-23 at 8 34 12 PM](https://user-images.githubusercontent.com/44647381/147284749-c1147703-5eae-4134-8e1a-ce7d4ac6a4db.png)

**Comment by edeckers** [comment]
Thank you for elaborating and once more for #177!

**For posterity**
Considering  your screenshot - which shows no complaints by Gradle about conflicting dependencies - and the slightly different error messages these issues are unrelated.
