### ISSUE TITLE
Warning: Module BlobCourierEventEmitter requires main queue setup ...

### ISSUE THREAD

**Issue by rezasazesh** [edeckers/react-native-blob-courier#128]
**Describe the bug**

Thank you for this great library since the other blob managers are not maintained. Since I installed this packaged I am getting the yellow box warning below. Nothing that stops my work but was wondering if it is something that needs to be fixed

**To Reproduce**
1. Install react-native-blob-courier according to instructions
2. Run RN Project

**Expected behavior**
Not have yellow box warning

**Screenshots**
![image](https://user-images.githubusercontent.com/45229791/107460377-20933f80-6bac-11eb-8559-db5580a0a7f9.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by edeckers** [comment]
Hi @rezasazesh , great to hear you enjoy the library, and thank you for your thorough bug report! I've put this issue on the [backlog](https://github.com/edeckers/react-native-blob-courier/projects/1) and I plan to fix it after I release the cancellation feature https://github.com/edeckers/react-native-blob-courier/pull/123.
