### ISSUE TITLE
[IOS] Accept PUT method in BlobUploader.swift

### ISSUE THREAD

**Issue by vforvasile** [edeckers/react-native-blob-courier#156]
Hey!

**Is your feature request related to a problem? Please describe.**
I can't upload media using **POST** method cause I use S3 presigned url which requires **PUT** method.

**Describe the solution you'd like**
Inside **BlobCourier.uploadBlob** params, make the _method_ prop communicate with the Swift file.

**Describe alternatives you've considered**
I can make a small change with a patch and a hardcoded value but that's a solution just for me.

Thanks for listening!

**Comment by edeckers** [comment]
Hi @vforvasile, thank you for your report! I took a quick peek and this issue looks like a huge oversight by me from start to finish, wow. Seems alright on the Android code base luckily.

Unfortunately I don't expect to work on this issue myself before the second week of August though. I'll keep you posted through the dedicated [issue](#158) I created.
