### ISSUE TITLE
[Android] Build error in RN 0.65

### ISSUE THREAD

**Issue by kkoudev** [edeckers/react-native-blob-courier#160]
**Describe the bug**
Build error in RN 0.65.

**To Reproduce**
1. Upgrade to RN 0.65
2. react-native run-android.

**Expected behavior**
Successful build in RN 0.65.

**Smartphone (please complete the following information):**
 - Device: all Android
 - OS: all Android
 - Browser: not applicable
 - Version: all

**Additional context**
I think this issue is probably due to the okhttp version being upgraded with RN 0.65.

**Comment by edeckers** [comment]
Hey @kkoudev, thank you for reporting this issue! I created issue #162 to track progress.

Also, I've already fixed most of the problem in PR https://github.com/edeckers/react-native-blob-courier/pull/161, but I need to do some more testing with `pre-0.65` versions of RN especially to ensure everything still works as expected. Hopefully I'll get around doing so this week.

**Comment by kkoudev** [comment]
@edeckers Thanks!
