### ISSUE TITLE
Receiving TypeVariable(T) error when ejecting Expo 39 / RN0.63

### ISSUE THREAD

**Issue by edeckers** [edeckers/react-native-blob-courier#180]
See https://github.com/edeckers/react-native-blob-courier/issues/106#issuecomment-1000437370 for the original report by @majirosstefan.

And his fix that resolved the issue for him https://github.com/edeckers/react-native-blob-courier/pull/177

**Describe the bug**
Running the app crashes on the Android build with:
```
(...)
main/java/io/deckers/blob_courier/upload/UploaderParameterFactory.kt: (113, 16): Type mismatch: inferred type is ReadableMap? but TypeVariable(T) was expected
(...)
```

**To Reproduce**
1. Use library in Expo app
2. Eject the app
3. Run `npx react-native run-android`

**Expected behavior**
The app is expected to build, without any issues.

**Smartphone (please complete the following information):**
 - OS: Android

**Additional context**
```
- expo ^39.0.0
- react-native ~0.63.4
- react-native-blob-courier ^3.0.0
```

**Comment by majirosstefan** [comment]
The project is not open-source, so  I cannot share links to the repo.

Some more additional information: 

  ext {
        buildToolsVersion = "30.0.0"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        kotlin_version = "1.4.21"
        kotlinVersion = "1.4.21"
        RNNKotlinVersion = kotlinVersion
    }
    
    dependencies {
        classpath("com.android.tools.build:gradle:4.0.2")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath("com.google.gms:google-services:4.3.8")

        // for blob-courier
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
    } 
    
Android Studio 4.1.1
    
```
    System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 106.90 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.4 - ~/.nvm/versions/node/v12.22.4/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v12.22.4/bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v12.22.4/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_202 - /Users/stefanmajiros/.jenv/shims/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```    
       
As you are mentioning here, https://github.com/edeckers/react-native-blob-courier/pull/177#issuecomment-1000879406, I may be using an incompatible Kotlin version - but I have no idea, how to investigate what the proper Kotlin version should be.

+ If I remember correctly, expo-constants was also using Kotlin.

**Comment by edeckers** [comment]
Thanks a bunch, this should help! I'm currently working on another PR and I plan to dive into your issue after finishing said PR.

**Comment by edeckers** [comment]
I managed to reproduce your issue by following the reproduction steps in the description of this PR, which helped me to narrow the issue down to the React Native version used: I've been testing the library against `0.64.2`, while your app uses `0.63.4`. Upgrading `0.63.4` to `>= 0.64.2` fixes the issue, but I'm not sure if that works for your situation?

Then there remains the problem that I'm still unsure of the actual cause, so I'll have to dive a little deeper on a later moment, but I wanted to give you a heads-up my progress, maybe it helps you.

**Comment by edeckers** [comment]
Alright, found the problem in `ReadableMap` where `@Nullable` changed to `@NonNullable`! Can you believe it:
https://github.com/facebook/react-native/commit/d76556543f96f4d739be3a708b8f6314bb32cc87#diff-0e6bf5ba9ff458815fd5bcabdf75c1659e41e3365bd260b26089c1863793113cL36

So I guess I will be using your PR after all and surpress the linter error with a comment explaining the situation.
