### ISSUE TITLE
Replace JCenter with suitable alternative

### ISSUE THREAD

**Issue by edeckers** [edeckers/react-native-blob-courier#187]
On [February 3rd 2021](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) JFrog [announced](https://blog.gradle.org/jcenter-shutdown) they will shutdown JCenter, which means `react-native-blob-courier` should move away from it. 

**Solution**
All `jcenter` repository occurences are replaced with a suitable alternative.

**Comment by limaCoder** [comment]
Hi @edeckers! I updated the package version to the latest published (3.0.4), and it's still getting the same error related here, on the build time :(

**Comment by edeckers** [comment]
Oh no, you mean this error still occurs https://github.com/edeckers/react-native-blob-courier/issues/186? Or you mean the `jcenter`  warnings?

**Comment by limaCoder** [comment]
sorry, I have commented on the wrong place, the `jcenter` disappeared, but the error on issue #186 still occurs.

**Comment by limaCoder** [comment]
Sorry @edeckers, I have commented in the wrong place, the `jcenter `disappeared, but the error on issue #186 still occurs.

**Comment by edeckers** [comment]
Alright, let's discuss there.
