### ISSUE TITLE
Module '"react-native"' has no exported member 'NativeEventEmitter'.ts(2305)

### ISSUE THREAD

**Issue by zhuernm** [edeckers/react-native-blob-courier#216]
**Describe the bug**
RN version is 0.67.4.
This version is not supported?

**Screenshots**
![image](https://user-images.githubusercontent.com/21044913/167997682-07ae2cba-9dc0-4cce-b11e-7015b922b6e4.png)

![image](https://user-images.githubusercontent.com/21044913/167997497-65091f97-7d7a-4e09-95d9-04c9ab4ffe6b.png)

**Comment by edeckers** [comment]
Hi @zhuernm , thank you for posting this issue! The library is supposed to support all React Native `>= 0.63.x` versions, so I looked into this problem by trying to reproduce it in a fresh app and I managed to use `react-native-blob-courier@3.0.9` on React Native `0.67.4` just fine. What version of `react-native-blob-courier` are you using?

These are my reproduction steps:
1. Run `npx react-native init RnTest0674 --template react-native-template-typescript@6.9.6`
2. Apply the patch below, by saving it somewhere on your development machine and running `patch -p0 < /path/to/test.patch`

```
--- package.json	2022-05-12 09:55:35.624635026 +0200
+++ package.json	2022-05-12 09:57:26.629894991 +0200
@@ -14 +14,2 @@
-    "react-native": "0.67.4"
+    "react-native": "0.67.4",
+    "react-native-blob-courier": "^3.0.9"
--- App.tsx	2022-05-12 09:55:35.624635026 +0200
+++ App.tsx	2022-05-12 10:00:19.755356070 +0200
@@ -11 +11,2 @@
-import React from 'react';
+import React, {useEffect} from 'react';
+import BlobCourier from 'react-native-blob-courier';
@@ -63,0 +65,17 @@
+
+  useEffect(() => {
+    const fetchFile = async () => {
+      // Download a file
+      const request0 = {
+        filename: '5MB.zip',
+        method: 'GET',
+        mimeType: 'application/zip',
+        url: 'http://ipv4.download.thinkbroadband.com/5MB.zip',
+      };
+
+      const fetchedResult = await BlobCourier.fetchBlob(request0);
+      console.log(fetchedResult);
+    };
+
+    fetchFile();
+  }, []);
```

Output:
```bash
LOG  {"data": {"absoluteFilePath": "file:///data/user/0/com.rntest0674/cache/5MB.zip", "response": {"code": 200, "headers": [Object]}}, "type": "Unmanaged"}
```
