### ISSUE TITLE
Missing content-type boundary

### ISSUE THREAD

**Issue by crzycoder** [edeckers/react-native-blob-courier#229]
**Describe the bug**
Missing content-type boundary on IOS while uploading image

**To Reproduce**
   ```
try {
      const uploadResult = await BlobCourier.settings({
        progressIntervalMilliseconds: 200,
        signal: abortController.signal,
      })
        .onProgress(e => {
          console.log('written-->>>', e.written / e.total);
        })
        .uploadBlob({
          absoluteFilePath: path,
          method: 'POST',
          mimeType: 'application/jpg',
          returnResponse: true,
          headers: {
            // 'content-type': 'multipart/form-data; ',
            'content-type': 'multipart/form-data',
            Authorization: 'Bearer ' + accessToken,
          },
          url: url,
        });
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by edeckers** [comment]
Hi @crzycoder , thank you for opening this issue! I haven't been able to verify on an actual device yet, but from the code it seems that `Content-Type` is always set.

https://github.com/edeckers/react-native-blob-courier/blob/2b2fa7c76e72b1c62a17e30fe71c5ebfa58db6fc/ios/Upload/BlobUploader.swift#L29

Could you please elaborate a bit further about the problem at hand? e.g. what is it you try to achieve, what do you expect to happen, what actually happens?

**Comment by crzycoder** [comment]
I'm closing the issue..
The Issue is related to content-type which you mentioned is already set.
