### ISSUE TITLE
is add body？

### ISSUE THREAD

**Issue by skyliwq** [edeckers/react-native-blob-courier#62]
```tsx
const request = {
    absoluteFilePath: image.sourceURL,
    method: 'POST',
    mimeType: image.mime,
    url: OSS.host,
    returnResponse: true,
    headers: {
    'Content-Type': 'multipart/form-data',
    },
    body: {
      policy: OSS.policy,
      OSSAccessKeyId: OSS.accessid,
      signature: OSS.signature,
      callback: OSS.callback,
      'x:token ': token,
      key: OSS.dir + imageName,
      success_action_status: 200,
      file: image.sourceURL,
    },
};
```

**Comment by edeckers** [comment]
Hi @skyliwq, thanks for reaching out. Just to make sure what you're asking: you want to be able to send a body with your file upload requests?

**Comment by skyliwq** [comment]
Thank you very much for the project you have developed. Many times we all need to upload files and carry body to the server. I hope to add this function. Thank you very much for your efforts on this project.

**Comment by edeckers** [comment]
Sounds like a good feature, I've created a feature issue (#63), in which I'll share my progress!

Have you done any work on it yourself, that you would like to share?

**Comment by edeckers** [comment]
Closing this in favor of #63
