### ISSUE TITLE
The body of your POST request is not well-formed on iOS

### ISSUE THREAD

**Issue by skyliwq** [edeckers/react-native-blob-courier#83]
`Content-Disposition: form-data;Name="{key}"\r\n\n{value}\r\n--{boundary}` sends without problems in this format, such as rn-fetch-blob. `{name: 'policy', data: OSS.policy}....`

my code

 ```tsx
BlobCourier.uploadParts({
    method: 'POST',
    returnResponse: true,
    filename: imageName,
    parts: {
      policy: {
        payload: OSS.policy,
        type: 'string',
      },
      file: {
        payload: {
          absoluteFilePath: absoluteFilePath,
          mimeType: 'application/' + imageType,
        },
        type: 'file',
      },
    },
    url: OSS.host,
})
```

**Comment by edeckers** [comment]
Hey @skyliwq thank you for reaching out once more,o I'll have a look at it! And I'll keep you posted on the progress.

**Comment by skyliwq** [comment]
Android normal iOS error

**Comment by edeckers** [comment]
Alright, that's helpful. And that's what I was afraid of: on iOS I build each part of the POST-body manually as that seems to be the way it is done on iOS. I'll check it out.
