### ISSUE TITLE
please check the order of the fields

### ISSUE THREAD

**Issue by skyliwq** [edeckers/react-native-blob-courier#84]
I have requirements for the order of body fields. can they be arranged in an orderly manner? Please check the order of fields.

**Comment by edeckers** [comment]
Are they not processed in the order you provide them? On which platform are you experiencing this?

**Comment by skyliwq** [comment]
android

**Comment by skyliwq** [comment]
I have tested it both android and ios have this problem

**Comment by edeckers** [comment]
Thank you for investigating. I'll look in to it when I find a moment!

**Comment by edeckers** [comment]
Closing this ticket in favor of #91
