### ISSUE TITLE
Depend less on GitHub actions

### ISSUE THREAD

**Issue by edeckers** [edeckers/react-native-blob-courier#95]
At the moment, all build and test steps are defined in `ci.yml`. These steps need to be moved to proper build and test scripts, maybe even a `Makefile`, which in turn should be called from `ci.yml`.

**Comment by mgambati** [comment]
Would you like to add [semantic-release](https://github.com/semantic-release/semantic-release) support? I will really help with the release process.

I have some experience with it and I can help with it. But I can say that it will not reduce the dependency on Github Actions...

**Comment by edeckers** [comment]
Hi @mgambati, thank you for reaching out and offering your help! I really appreciate that :)

A few observations:
1. The "depending less on GitHub Actions" title was chosen a little poorly by me: the goal of this ticket is to introduce an easy means of executing all build steps on a local machine, instead of pushing the changes to CI and hoping for the best. I exaggerate, but you catch my drift;
2. In addition to (1), it is really not an issue if the current CI workflow becomes more complex and dependent on GitHub Actions, if necessary;
3. I _do_ like to incorporate a release step sometime soon, but I am reluctant to add a dependency for this step, since building and deploying a release at this moment is really just a oneliner.

What do you say I think about how I want to go about this, and if I decide to use [semantic-release](https://github.com/semantic-release/semantic-release), I'll create an issue in my repository and mention you? We can then divide the work among the two of us.
